all:                                                                            
	ocamlbuild -use-ocamlfind -package qcheck qchecktest.byte
                                                                                
clean:                                                                          
	ocamlbuild -clean